import Link from 'next/link';
import { Card } from '@/components/card';
import { MediaImage } from '@/components/portfolio/media-image';
import { ProjectCarousel } from '@/components/project-carousel';
import { SectionHeading } from '@/components/section-heading';
import { repository } from '@/lib/portfolio-repository';
import { TeammateFeedback } from '@/components/teammate-feedback';
import { testimonials } from '@/data/testimonials';

const projectVisuals = {
  'sepia-client': { src: '/images/optimized/projects/sepia/sepia-overview.jpg', alt: 'SEPIA desktop creator interface, rack, and hardware module arranged as one centered visual group', label: 'SEPIA software-to-hardware platform' },
  'qpro': { src: '/images/optimized/projects/QPRO/qpro-overview.jpg', alt: 'QPRO queue management overview with a large teller dashboard on the left and an overlapping mobile service-lane flow on the right', label: 'QPRO queue management system' },
  'fast': { src: '/images/optimized/projects/FAST/fast-overview.jpg', alt: 'FAST document intelligence overview with a large desktop OCR search interface and an overlapping mobile document vault', label: 'FAST document intelligence platform' },
  'availbld': { src: '/images/optimized/projects/availbld/availbld-overview.jpg', alt: 'Four Availbld mobile screens showing live event feeds, instant groups, event chat, and event discovery', label: 'Availbld event coordination' },
  'metacare': { src: '/images/optimized/projects/Metacare/metacare-overview.jpg', alt: 'Four MetaCare mobile screens showing the health marketplace home, member benefits, product discovery, and order summary', label: 'MetaCare health and wellness marketplace' },
  'awh-app': { src: '/images/optimized/projects/AWH/awh-overview.jpg', alt: 'AWH warehouse operations overview showing inventory, dispatch, scanner, field operator, zone density, and system synchronization panels', label: 'AWH warehouse operations platform' },
};

export default function Home() {
  const capabilities = repository.listCapabilities();
  const projects = repository.listProjects().slice(0, 4);
  const stories = repository.listStories();
  const featuredStories = ['device-lifecycle-management', 'configuration-recovery', 'hardware-communication-platform']
    .map((slug) => stories.find((story) => story.slug === slug))
    .filter((story): story is (typeof stories)[number] => Boolean(story));

  return (
    <>
      <section className="home-hero" aria-labelledby="hero-heading">
        <div className="hero-grid mx-auto grid max-w-6xl grid-cols-1 items-center gap-8 px-5 pb-24 pt-12 lg:grid-cols-12 md:pb-28 md:pt-16">
          <div className="lg:col-span-7">
            <p className="mb-5 font-mono text-xs uppercase tracking-[.18em] text-[var(--accent)]">Senior cross-platform systems engineer</p>
            <h1 id="hero-heading" className="max-w-3xl text-4xl font-semibold leading-[1.05] tracking-[-.04em] md:text-6xl">I build dependable products across software, native systems, and connected devices.</h1>
            <div className="hero-actions mt-8 flex flex-wrap items-center gap-3"><Link href="#projects" className="hero-primary-cta inline-flex min-h-12 items-center rounded-full bg-[var(--accent)] px-6 py-3 text-sm font-semibold text-[#082522] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--accent)]">View selected projects <span aria-hidden="true" className="ml-2">↘</span></Link><Link href="/profile" className="hero-secondary-link inline-flex min-h-12 items-center rounded-full border border-[var(--line)] px-5 py-3 text-sm font-medium text-[var(--muted)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--accent)]">Open my profile <span aria-hidden="true" className="ml-2">↗</span></Link></div>
          </div>
          <figure className="hero-boundary-card rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 lg:col-span-5 lg:mt-8 md:p-7"><p className="font-mono text-xs uppercase tracking-[.18em] text-[var(--accent)]">/ system boundary</p><p className="mt-2 text-lg font-medium">Make the handoffs visible.</p><ol className="diagram-flow mt-6" aria-label="A conceptual path from user intent to connected hardware"><li className="diagram-step"><span className="diagram-step-index">01</span><span className="diagram-node">User intent + interface</span></li><li className="diagram-step"><span className="diagram-step-index">02</span><span className="diagram-node">Domain rules + durable state</span></li><li className="diagram-step"><span className="diagram-step-index">03</span><span className="diagram-node">Typed integration boundary</span></li><li className="diagram-step"><span className="diagram-step-index">04</span><span className="diagram-node">Connected device behavior</span></li></ol><figcaption className="hero-boundary-caption mt-5 pt-4 text-sm leading-6 text-[var(--muted)]">Clear ownership helps software stay understandable when systems change.</figcaption></figure>
        </div>
      </section>
      <section id="projects" className="home-section home-section--projects mx-auto max-w-6xl px-5 py-20" aria-labelledby="projects-heading"><SectionHeading kicker="01 / selected projects" title="Products shaped by real system constraints" id="projects-heading">A focused look at the product context and engineering boundaries behind the work.</SectionHeading><ProjectCarousel projects={projects} visuals={projectVisuals} /></section>
      <section id="about" className="home-section border-y border-[var(--line)] bg-[var(--surface)]" aria-labelledby="about-heading"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-20 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><figure className="profile-portrait mx-0 max-w-sm" aria-label="Portrait of Felix Edrian Ybañez"><MediaImage src="/images/felix_edrian_ybanez.jpg" alt="Felix Edrian Ybañez" fill sizes="(max-width: 64rem) 100vw, 28rem" /></figure><div><SectionHeading id="about-heading" kicker="02 / about me" title="Calm, explicit, and collaborative">I make complex software easier to change, especially when state, hardware, and people all need to stay aligned.</SectionHeading><ol className="about-lens-list mt-7 grid gap-3 sm:grid-cols-2" aria-label="Engineering principles"><li className="rounded-xl border border-[var(--line)] bg-[var(--bg)] p-4 text-sm"><strong className="block text-[var(--accent)]">01 / Make ownership explicit</strong><span className="mt-2 block text-[var(--muted)]">Every important state transition should have a clear owner, lifecycle, and cleanup path.</span></li><li className="rounded-xl border border-[var(--line)] bg-[var(--bg)] p-4 text-sm"><strong className="block text-[var(--accent)]">02 / Preserve user intent</strong><span className="mt-2 block text-[var(--muted)]">Durable decisions should remain distinct from transient runtime state and external feedback.</span></li><li className="rounded-xl border border-[var(--line)] bg-[var(--bg)] p-4 text-sm"><strong className="block text-[var(--accent)]">03 / Design for the unhappy path</strong><span className="mt-2 block text-[var(--muted)]">Reconnects, partial failures, and asynchronous events are part of the product—not edge cases.</span></li><li className="rounded-xl border border-[var(--line)] bg-[var(--bg)] p-4 text-sm"><strong className="block text-[var(--accent)]">04 / Keep complexity changeable</strong><span className="mt-2 block text-[var(--muted)]">Typed seams, layered tests, and understandable boundaries make difficult systems safer to evolve.</span></li></ol><Link href="/profile" className="about-profile-link mt-7 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--accent)]">Read the full engineering profile <span aria-hidden="true">↗</span></Link></div></div></section>
      <section id="testimonials" className="home-section mx-auto max-w-6xl px-5 py-20" aria-labelledby="testimonials-heading"><SectionHeading kicker="03 / recommendations" title="Trusted in the difficult parts of delivery" id="testimonials-heading">A small proof strip from published feedback by people who worked with Felix.</SectionHeading><TeammateFeedback testimonials={testimonials.slice(0, 4)} /><Link href="/testimonials" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--accent)]">Read all testimonials <span aria-hidden="true">↗</span></Link></section>
      <section id="capabilities" className="home-section border-t border-[var(--line)] mx-auto max-w-6xl px-5 py-20" aria-labelledby="capabilities-heading"><SectionHeading kicker="04 / capability map" title="The engineering shape of the work" id="capabilities-heading">High-level areas connected to published project evidence, not a wall of tools.</SectionHeading><div className="grid gap-4 md:grid-cols-2">{capabilities.slice(0, 4).map((capability, index) => <Card key={capability.slug} href={`/capabilities/${capability.slug}`} eyebrow={`0${index + 1} / ${capability.category}`} title={capability.metadata.homepageTitle ?? capability.title} summary={capability.metadata.homepageSummary ?? capability.summary} tags={capability.tags.slice(0, 3)} />)}</div><Link href="/capabilities" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--accent)]">View the full capability map <span aria-hidden="true">↗</span></Link></section>
      <section id="stories" className="home-section mx-auto max-w-6xl px-5 py-20" aria-labelledby="stories-heading"><SectionHeading kicker="05 / engineering stories" title="The deeper questions, in compact form" id="stories-heading">Architecture, reliability, recovery, and testing stories from the published material.</SectionHeading><div className="grid gap-4 md:grid-cols-3">{featuredStories.map((story, index) => <Card key={story.slug} href={`/engineering-stories/${story.slug}`} eyebrow={`0${index + 1} / story`} title={story.metadata.homepageTitle ?? story.title} summary={story.metadata.homepageSummary ?? story.summary} tags={story.tags.slice(0, 3)} />)}</div><Link href="/engineering-stories" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--accent)]">Explore all engineering stories <span aria-hidden="true">↗</span></Link></section>
      <section className="mx-auto max-w-6xl px-5 pb-24" aria-labelledby="hire-heading"><div className="home-hire-card rounded-2xl border border-[var(--accent)] bg-[var(--accent-soft)] p-8 md:p-12"><p className="font-mono text-xs uppercase tracking-[.2em] text-[var(--accent)]">06 / hiring</p><h2 id="hire-heading" className="mt-5 max-w-2xl text-3xl font-semibold leading-tight md:text-4xl">Hiring for senior Flutter, cross-platform, or systems-oriented engineering work?</h2><p className="mt-4 max-w-2xl leading-7 text-[var(--muted)]">Let’s discuss the role, the product, and the engineering problems the team is solving.</p><Link href="/contact" className="mt-8 inline-flex min-h-12 items-center rounded-full bg-[var(--accent)] px-6 py-3 text-sm font-semibold text-[#082522] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--accent)]">Discuss a role <span aria-hidden="true" className="ml-2">↗</span></Link></div></section>
    </>
  );
}
